### ISSUE TITLE
mpi4py has pre-link warning causing an ImportError("Please install mpi4py")?

### ISSUE THREAD

**Issue by bkornpob** [guillochon/MOSFiT#129]
Hi,

I follow the installation of MOSFiT from the website by using Anaconda (in Windows 10). Even though "conda install -c conda-forge mosfit" cannot successfully install the program because of some issues, I manage to install individual packages successfully. Only mpi4py seems to have an issue with pre-link script as the warning says: "C:\Users\...\conda\core\link.py:475: UserWarning: Package defaults::mpi4py-2.0.0-py36_1 uses a pre-link script. Pre-link scripts are potentially dangerous. This is because pre-link scripts have the ability to change the package contents in the package cache, and therefore modify the underlying files for already-created conda environments. Future versions of conda may deprecate and ignore pre-link scripts."

I run "mosfit" and the MOSFiT logo shows up, but there is an error with mpi4py as says: "File "C:\Users\...\site-packages\schwimmbad\mpi.py", line 24, in _import_mpi raise ImportError("Please install mpi4py") 
ImportError: Please install mpi4py."

I check with "conda list" and see that "mpi4py 2.0.0 py36_1" is installed. I try "conda uninstall mpi4py" (which removes mosfit, mpi4py, and schwimmbad all together) and re-install them back. The same issue happens with pre-link script and ImportError.

Please help. Thank you.

**Comment by guillochon** [comment]
Hi @bkornpob, thanks for creating the issue. I believe that the pre-link error your seeing is only a warning for now, `mpi4py` should still have installed. You should probably check to see if the `mpi4py` package is indeed installed and if you can import it in a small test script (a minimum reproducible example).

`mpi4py` is definitely not required for MOSFiT to operate properly, but the code is currently importing `schwimmbad` even in serial mode, which is causing the import error you're seeing. The fact that MOSFiT won't run without `mpi4py` installed is an oversight I will correct.

**Comment by guillochon** [comment]
`mpi4py` should no longer need to be installed in the latest commit (https://github.com/guillochon/MOSFiT/commit/5061c97a99a83780354046c785170217d2611a2f). I will push a version to conda-forge, which can take several hours, so I'd recommend cloning directly from the GitHub repo via `python setup.py install` if you want to get going right away!

**Comment by bkornpob** [comment]
It is working now. Thank you very much.
