### ISSUE TITLE
Is there any discussion board for how to use?

### ISSUE THREAD

**Issue by bkornpob** [guillochon/MOSFiT#134]
Hi,

I forgot to introduce myself in the previous message. I am Kornpob, a Ph.D. student at Ohio University. My research is about SLSNe and powering mechanisms.

I wonder if there is any discussion board that I can ask questions about how to use MOSFiT; I don't think I should put those questions here.

Thank you.

**Comment by guillochon** [comment]
Hi @bkornpob, we have a Slack channel that's probably best, fire me an e-mail (guillochon@gmail.com) and I'll invite you to it.

**Comment by bkornpob** [comment]
My email is bkornpob@gmail.com.
