### ISSUE TITLE
BUG: String Decoding 

### ISSUE THREAD

**Issue by pcowpert** [guillochon/MOSFiT#135]
I have a fresh install of Anaconda (Python 3.6.3) on my Linux Desktop (CentOS 6.9). I was able to install MOSFiT without issue.

However, when I run a simple test  command like:

`mosfit -e LSQ12dlf -m slsn
`

I get the traceback error:

```pcowpert deckard 58> mosfit -e LSQ12dlf -m slsn
ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 12148: ordinal not in range(128) [encodings.ascii]
Traceback (most recent call last):
  File "/pool/deckard0/anaconda3/bin/mosfit", line 11, in <module>
    load_entry_point('mosfit', 'console_scripts', 'mosfit')()
  File "/pool/deckard0/MOSFiT/mosfit/main.py", line 635, in main
    exit_on_prompt=args.exit_on_prompt
  File "/pool/deckard0/MOSFiT/mosfit/printer.py", line 74, in __init__
    self.set_strings()
  File "/pool/deckard0/MOSFiT/mosfit/printer.py", line 81, in set_strings
    strings = json.load(f, object_pairs_hook=OrderedDict)
  File "/pool/deckard0/anaconda3/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/pool/deckard0/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 12148: ordinal not in range(128)
```

The string object that it is attempting to decode is:

`<_io.TextIOWrapper name='/pool/deckard0/MOSFiT/mosfit/strings.json' mode='r' encoding='ANSI_X3.4-1968'>
`

The exact point of failure occurs when trying to read 'strings.json'. However, I have the exact same installation on another machine (Odyssey) and that is running with zero errors, so I don't think the issue is with the JSON file itself.

**Comment by guillochon** [comment]
@pcowpert Can you tell me if the following change works, replace line 79 in `printer.py` with:

            with open(os.path.join(
                dir_path, 'strings.json'), encoding='utf-8') as f:

**Comment by pcowpert** [comment]
@guillochon Yes that works. Thanks!

**Comment by guillochon** [comment]
Fixed in https://github.com/guillochon/MOSFiT/commit/5305558a5f19fe810a59c24090dc7b0fde4d77e7.

**Comment by pcowpert** [comment]
Jumped the gun. This error also occurs when the code goes to fetch data.

```
File "/pool/deckard0/MOSFiT/mosfit/fetcher.py", line 213, in fetch
   f, object_pairs_hook=OrderedDict)
```

Changing line 211: `with open(path, 'r') as f:`
to `with open(path, 'r', encoding = 'utf-8') as f:` will fix the issue.

It is fitting normally now. I'll make sure everything is output properly before closing the issue.

**Comment by guillochon** [comment]
Yes I'll need to generically change a few open calls where it could be loading unicode data. Typically this is just someone with an `ñ` in their name or something, or `µ`. I'll replace a few other places where this could be happening.

**Comment by guillochon** [comment]
The one you mentioned above fixed in https://github.com/guillochon/MOSFiT/commit/0235f02b6e9d77dc7cd786b570141a863e18eb89.
