### ISSUE TITLE
Not printing full band list?

### ISSUE THREAD

**Issue by villrv** [guillochon/MOSFiT#157]
MOSFiT typically lists the bands being used in the fit:

```
Loading bands complete.

Bands being used for current transient:
```

In one instance, I tried to fit a LC with ugrizy data, but it only listed g and r as the bands being used in the fitting process. However, when I looked at the output file, it did produce ugrizy bands. I believe the program was in fact fitting all of the bands, but only printed two of the filters being used.

This may be due to having only 1 data point in the uizy filters?

**Comment by guillochon** [comment]
This is actually a printing issue where Python `print`'s `flush` argument is being ignored for some reason. Adding a `sys.stdout.flush()` call after printing the covariance square seems to fix things, as is done in https://github.com/guillochon/MOSFiT/commit/eb5682b1c133645586f4cb618a9efec8a9f52b8b.
