### ISSUE TITLE
Automatically pull filters from SVO

### ISSUE THREAD

**Issue by guillochon** [guillochon/MOSFiT#16]
This looks really useful for pulling filter files, although there are some notable omissions: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=browse

If this particular solution doesn't work out, one similar to it would be fantastic to draw from.

**Comment by mnicholl** [comment]
In terms of standardising the wavelength intervals for filters, I think this is absolutely the best way to go. I'd suggest that wherever possible, we replace the filters in the code with ones available here.

**Comment by guillochon** [comment]
This has now been implemented, closing.
