### ISSUE TITLE
Early-time extrapolations not working

### ISSUE THREAD

**Issue by mnicholl** [guillochon/MOSFiT#161]
-E flag no longer seems to do the early time extrapolation, i.e. before first data point (but still works for late time, i.e. after the last data point)

The newer --extra-times (and related) flags seem to work only when dates are specified in MJD, but not when given in terms of a relative phase

**Comment by guillochon** [comment]
So @mnicholl there's a separate flag, `--extra-phases`, if you want to specify the extra times in terms of phase.

Looking into the `-E` flag now...

**Comment by mnicholl** [comment]
Yeah I used that too but it didn’t work

**Comment by guillochon** [comment]
OK, looking into both issues.

**Comment by guillochon** [comment]
Believe I've fixed both issues in https://github.com/guillochon/MOSFiT/commit/439a6a6dfd0580168933513c382b245487890d4c. Can you test?
