### ISSUE TITLE
Unable to read in many files

### ISSUE THREAD

**Issue by villrv** [guillochon/MOSFiT#17]
Of the first 10 SNe on sne.space (listed in #of data points), I can only read in 03dh and 09ip. For all the others, I get an error:

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/__main__.py", line 6, in <module>
>     main.main()
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/main.py", line 293, in main
>     Fitter().fit_events(**fitargs)
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/fitter.py", line 195, in fit_events
>     post_burn=post_burn)
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/fitter.py", line 231, in load_data
>     [0.0 for x in range(self._model._num_free_parameters)])
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/model.py", line 335, in likelihood
>     outputs = self.run_stack(x, root='objective')
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/model.py", line 384, in run_stack
>     new_outs = self._modules[task].process(**inputs)
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/modules/objectives/likelihood.py", line 40, in process
>     self._upper_limits)
>   File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/modules/objectives/likelihood.py", line 39, in <listcomp>
>     for x, y, z, u in zip(self._model_mags, self._mags, self._e_mags,
> TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'
>

**Comment by guillochon** [comment]
Guessing here this is a quick fix, just not converting a string to a float somewhere. Will look into it.

**Comment by guillochon** [comment]
OK, so this was because many of the top events on the list have no error bars for the detections, and before there was no default error bar for such points. I've now added such an option in https://github.com/guillochon/MOSFiT/commit/344776b58262fdcd51b1aa8c2274352fe2d19af2, by default errors of 1.0 mag will be used if a detection has no error bar. The setting can be changed with the `default_no_error_bar_error` parameter in model.json.

Although slow because they have many points, both 1987A and 1993J (which have no error bars) worked fine now with this patch. Gonna close!

**Comment by mnicholl** [comment]
Default error bar of 1 mag? Seems awfully large! I think in general if no error bar is quoted it's probably a well observed historical event and the real error would be a lot lot smaller... though I guess we don't know that a priori for all SNe that don't have error bars...

**Comment by guillochon** [comment]
It's almost certainly larger than any real error bar; but I wanted to make sure that a stray point with no error bar does not provide more leverage than one with an error bar. This is easily changed though by altering the `default_no_error_bar_error` parameter though.

I've actually reworked a few of the top SNe to use the error bars available for them in the literature, ITEP's tables typically don't include error bars; in general we should be trying to replace any data that doesn't have an error bar with better data.
