### ISSUE TITLE
(small bug) when running csmni - incorrect qoutation marks

### ISSUE THREAD

**Issue by Astro-Sean** [guillochon/MOSFiT#216]
Hi all,

I ran into a issue when running a csmni model. 

Line ~103 of csmni.json is currently (Mosfit v1.1.9):
```
    "kinetic_energy":{
        "kind":"parameter",
        "value":1.0,
        "class":"parameter",
        "latex":“E_{\\rm k}\\,(10^{51}\\,{\\rm erg})” # <- this line has incorrect quotation marks
    },
``` 

whereas it should be 

```
    "kinetic_energy":{
        "kind":"parameter",
        "value":1.0,
        "class":"parameter",
        "latex":"E_{\\rm k}\\,(10^{51}\\,{\\rm erg})" 
    },
```
Correcting this line allows the code to run  on my machine with Python 3.9.13

All the best,

Sean

**Comment by mnicholl** [comment]
Thanks Sean, can you submit a pull request for this and I’ll merge it?
