### ISSUE TITLE
dynesty needs to be capped at v1.2.3

### ISSUE THREAD

**Issue by cylammarco** [guillochon/MOSFiT#217]
MOSFiT is incompatible with dynesty after the recent upgrade to v2 as their dynamic sampler returns 16 items:

https://github.com/joshspeagle/dynesty/blame/bb1c5d5f9504c9c3bbeffeeba28ce28806b42273/py/dynesty/dynamicsampler.py#L1380

in MOSTFiT's `nester.py`, it only handles 15:

https://github.com/guillochon/MOSFiT/blob/2193d2d05455bf3a3d9dd8ec3f828d5140f3677c/mosfit/samplers/nester.py#L131

**Comment by mnicholl** [comment]
The latest version of mosfit should now work with both dynesty v2 and older versions of dynesty. Marking as closed
