### ISSUE TITLE
Difficulty choosing walkers when fixing t_explosion?

### ISSUE THREAD

**Issue by villrv** [guillochon/MOSFiT#61]
When t_explosion is limited to t_explosion >= 0, mosfit takes a long time to initialize walkers. This is true even without an event. Fixing t_explosion=0 prevents the walkers from ever initializing.

**Comment by guillochon** [comment]
Having some difficulty reproducing this one. Could you paste the command that is causing the lockup?

**Comment by villrv** [comment]
"python -m mosfit -m magni -N 50" is causing it. However, in the parameters.json file, I have 

    "texplosion":{
        "value":0
    },

**Comment by guillochon** [comment]
Can reproduce now. Looking into it.

**Comment by guillochon** [comment]
This was a simple one, I had forgotten to flag `test = False` in serial mode when `iterations = 0`. Fixed in https://github.com/guillochon/MOSFiT/commit/f5a8b6178edc89c1aa0c924f6aaa603c8d98f1b1.
